
services:
  postgres:
    image: postgres:16
    container_name: advpro-postgres
    environment:
      POSTGRES_DB: advpro-2024
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
